### PR TITLE
fixed popup bug during registration

### PR DESCRIPTION
**Pull request by zh6ziq**
fixed annoying popup during validation on registration form

### CODE REVIEW

**Review by iqbalbaharum — CHANGES_REQUESTED** [review]
Register request is not supposed to been send on form error.

**Comment by zh6ziq** [comment]
Latest Commit

1. Blocked register request from been send on error.
2. Clean eslint.

**Review by iqbalbaharum — CHANGES_REQUESTED** [review]
Pull latest code from original

**Comment by zh6ziq** [comment]
Latest code updated

**Review by iqbalbaharum — APPROVED** [review]

**Pull request merged**
